### ISSUE TITLE
Some refactoring in Fragments and ViewModels

### ISSUE THREAD

**Issue by guerrk1n** [SobolevvMaxim/ForecastApp-Android-#36]
In each fragment you have something like "viewModel.errorLiveData.observe". that show to users same error messages. Maybe lets create a BaseViewModel and BaseFragment.
In abstract BaseViewModel:

    val error = MutableLiveData<Event<Throwable>>()
    protected fun showError(throwable: Throwable) {
        error.value = Event(throwable)
    }

    
And in BaseFragment:

    abstract class BaseFragment<T : BaseViewModel> : Fragment() {
    ...
    protected abstract val viewModel: T
    ...
    @CallSuper
    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)
        viewModel.error.observe(viewLifecycleOwner, EventObserver { showError(it) })
    }
    }

And then you can handle error in this class in showError fun, or delegate to handle such errors to other class (better solution as for me).

**Comment by SobolevvMaxim** [comment]
Maybe i should create request fun in BaseViewModel, so request will look like that: 
`private fun searchForecast(city: City) {
        networkRequest(
            _chosenLiveData,
            request = {
                getForecastUseCase(city)
            },
            successCallback = {
                writeCityToBaseUseCase(it)
            }
        )
    }`
And in MainFragment i will handle it like that: 
`private val cityObserver = Observer<Event<CityWeather>?> { city ->
        when (city.status) {
            Status.LOADING -> {
                loading_city_progress.updateProgressBar(true)
                Log.d(getString(R.string.main_log), "Loading...")
            }
            Status.SUCCESS -> city.data?.let {
                loading_city_progress.updateProgressBar(false)
                swipe_layout.isRefreshing = false
                checkToUpdate(it)
                updateView(it)
            } ?: run {
                viewModel.searchCityForecastByName(getString(R.string.default_city))
            }
            Status.ERROR -> Toast.makeText(requireContext(), "Error: ${city.error}", Toast.LENGTH_LONG).show()
        }
    }`
?
